services:
  nginx:
    build:
      context: ./nginx
    restart: always
    platform: linux/amd64
    ports:
      - "8080:80"
    depends_on:
      - app
      - db
    networks:
      - mynetwork
  app:
    # Aqui está o mapeamento de volumes do node
    volumes:
      - ./node:/usr/src/app
    build:
      context: ./node
    entrypoint: "wait-for db:3306 -t 30  -- ./entrypoint.sh"
    platform: linux/amd64
    networks:
      - mynetwork
    depends_on:
      - db
  db:
    build:
      context: ./mysql
    restart: always
    platform: linux/amd64
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql/volume:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
