version: "3.1"

services:
  nginx:
    build:
      context: ./nginx
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - mynetwork
  app:
    build:
      context: ./node
    entrypoint: "wait-for db:3306 -t 30  -- ./entrypoint.sh"
    volumes:
      - ./node:/app
    networks:
      - mynetwork
    depends_on:
      - db
  db:
    build:
      context: ./mysql
    restart: always
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql/volume:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
